### ISSUE TITLE
PSR 20

### ISSUE THREAD

**Issue by Spomky** [EventSaucePHP/Clock#2]
Hi,

Is it possible for the clock interface to extend the [PSR-20](https://www.php-fig.org/psr/psr-20/) interface?
As they are exactly the same, it seems to be feasible without any breaking change. It will help a Mr d avoid similar clock system to exist in tfe same project.

Many thanks.
Regards.

**Comment by markinigor** [comment]
@frankdejonge Can you accept this PR https://github.com/EventSaucePHP/Clock/pull/3

**Comment by frankdejonge** [comment]
Will look at this tonight, but looks simple enough 👍 will also check if we can switch to relying on the PSR interface in the main package

**Comment by frankdejonge** [comment]
Version 1.2.0 is released, which marks the clock an implementation of PSR-20.
